baseURL = "http://example.org/"
languageCode = "en-us"
title = "Timer | Responsive Multipurpose Bootstrap Hugo Template"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Navbar Menus
[[menu.main]]
name    = "Home"
url     = "/"
weight  = 1
[[menu.main]]
name    = "Our Services"
url     = "service"
weight  = 2
[[menu.main]]
name    = "Advantage"
url     = "gallery"
weight  = 3
[[menu.main]]
name    = "About"
url     = "about"
weight  = 4
[[menu.main]]
name    = "Contact"
url     = "contact"
weight  = 5
[[menu.main]]
name    = "Contact"
url     = "contact"
weight  = 6

# Site Params
[params]
home = "Home"
logo = "images/mesh_logo.png"
dateFormat = "6 January 2006"
# Meta data
description = "Airspace Hugo theme"
author = "Themefisher"
# Google Analitycs
googleAnalitycsID = "Your ID"
# contact form action
contactFormAction = "#" # contact form works with https://formspree.io

# Banner Section
[params.banner]
enable  = true
bgImage = "images/slider.jpg"
heading = "Skyrocket your revenue 100% done-for-you"
description = "MESH uses AI to send effective, personalized messages to your dream clients proven to get positive responses."
# button
btn     = true
btnText = "Free Consultation"
btnURL  = "https://themefisher.com/"

# flip text
[[params.banner.flipText]]
title   = "Save Time"
[[params.banner.flipText]]
title   = "Grow your Business"
[[params.banner.flipText]]
title   = "Friendly Support"

# Homepage About Section
[params.about]
enable  = true
title   = "ABOUT US"
content = "We have multi-year experience with proven record of employing state-of-the-art marketing techniques to attract more clients to any businesses. Our customers are from different industries such as Financial services, education institutes, Franchising institutes, real-estate brokers, commercial brokers, personal development coach, software development consultation companies, etc. We love what we do and we put our full expertise to work. Ask us about collaboration of becoming part of your business rather than working for you option! We believe every business is different. We need to understand your business, then we provide customized solution to your needs!"
image   = "images/about/about.jpg"

# Call to Action
[params.cta]
enable  = true
title   = "SO WHAT YOU THINK ?"
content = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis,<br>possimus commodi, fugiat magnam temporibus vero magni recusandae? Dolore, maxime praesentium."
btnText = "Contact with me"
btnURL  = "/contact"


# Portfolio Section On Homepage
#[params.portfolio]
#enable  = true
#title   = "Latest Works"
#subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

# social icon
[[params.socialIcon]]
icon = "ion-social-facebook"
url = "#"

[[params.socialIcon]]
icon = "ion-social-instagram"
url = "#"

[[params.socialIcon]]
icon = "ion-social-linkedin"
url = "#"
